/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.jdbc;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.dto.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.List;
import java.util.ArrayList;
import java.math.*;
import java.util.Date;
import org.nic.epanjeeyan.exceptions.*;
import org.nic.epanjeeyan.dto.AppointmentDetails;

public class AppointmentDetailsDaoImpl extends AbstractDAO implements AppointmentDetailsDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * This is the SQL statement defined for this Custom SQL DAO
	 */
	public static final String SQL = "SELECT appointment_id, applicant_name, appointment_date, n.name  FROM appointment_slot_booking a, nodal_officers n where a.officer_id=n.officer_id and a.sro_office=? and a.appointment_date like ?";

	/**
	 * Method 'AppointmentDetailsDaoImpl'
	 * 
	 */
	public AppointmentDetailsDaoImpl()
	{
	}

	/**
	 * Method 'AppointmentDetailsDaoImpl'
	 * 
	 * @param userConn
	 */
	public AppointmentDetailsDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/**
	 * Method 'executeDynamicSQL'
	 * 
	 * @param sql
	 * @param officeId
	 * @param appointmentDate
	 * @throws AppointmentDetailsDaoException
	 * @return AppointmentDetails[]
	 */
	public AppointmentDetails[] executeDynamicSQL(String sql, int officeId, String appointmentDate) throws AppointmentDetailsDaoException
	{
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		try {
			if (isConnSupplied) {
				conn = userConn;
			} else {
				conn = ResourceManager.getConnection();
			}
		
			System.out.println( "Executing " + sql );
			stmt = conn.prepareStatement(sql);
			stmt.setInt( 1, officeId );
			stmt.setString( 2, appointmentDate );
			rs = stmt.executeQuery();
			List list = new ArrayList();
			while (rs.next()) {
				AppointmentDetails dto = new AppointmentDetails();
				dto.setAppointmentId( rs.getString( 1 ) );
				dto.setApplicantName( rs.getString( 2 ) );
				dto.setAppointmentDate( rs.getTimestamp(3 ) );
				dto.setOfficerName( rs.getString( 4 ) );
				list.add( dto );
			}
		
			AppointmentDetails ret[] = new AppointmentDetails[ list.size() ];
			list.toArray( ret );
			return ret;
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AppointmentDetailsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/**
	 * Method 'execute'
	 * 
	 * @param officeId
	 * @param appointmentDate
	 * @throws AppointmentDetailsDaoException
	 * @return AppointmentDetails[]
	 */
	public AppointmentDetails[] execute(int officeId, String appointmentDate) throws AppointmentDetailsDaoException
	{
		return executeDynamicSQL( SQL, officeId, appointmentDate );
	}

	/** 
	 * Returns all rows from the AppointmentDetails table that match the specified arbitrary SQL statement
	 */
	public AppointmentDetails[] findByDynamicWhere(String sql, Object[] sqlParams) throws AppointmentDetailsDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			String _SQL = SQL;
			int sqlindex = SQL.toUpperCase().indexOf(" WHERE ");
			if (sqlindex >= 0) {
				StringBuffer s = new StringBuffer(_SQL);
				s.insert(sqlindex+7, sql+" AND ");
				_SQL = s.toString();
			} else {
				_SQL = SQL + " WHERE " + sql;
			}
		
		
		
			System.out.println( "Executing " + _SQL );
			// prepare statement
			stmt = conn.prepareStatement( _SQL );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			List list = new ArrayList();
			while (rs.next()) {
				AppointmentDetails dto = new AppointmentDetails();
				dto.setAppointmentId( rs.getString( 1 ) );
				dto.setApplicantName( rs.getString( 2 ) );
				dto.setAppointmentDate( rs.getTimestamp(3 ) );
				dto.setOfficerName( rs.getString( 4 ) );
				list.add( dto );
			}
		
			AppointmentDetails ret[] = new AppointmentDetails[ list.size() ];
			list.toArray( ret );
			return ret;
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AppointmentDetailsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
