/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.jdbc;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import java.util.Date;
import org.nic.epanjeeyan.dto.*;
import org.nic.epanjeeyan.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class AppointmentQueueDaoImpl extends AbstractDAO implements AppointmentQueueDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT appointment_id, officer_id, appointment_date FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( appointment_id, officer_id, appointment_date ) VALUES ( ?, ?, ? )";

	/** 
	 * Index of column appointment_id
	 */
	protected static final int COLUMN_APPOINTMENT_ID = 1;

	/** 
	 * Index of column officer_id
	 */
	protected static final int COLUMN_OFFICER_ID = 2;

	/** 
	 * Index of column appointment_date
	 */
	protected static final int COLUMN_APPOINTMENT_DATE = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Inserts a new row in the appointment_queue table.
	 */
	public void insert(AppointmentQueue dto) throws AppointmentQueueDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setString( index++, dto.getAppointmentId() );
			stmt.setInt( index++, dto.getOfficerId() );
			stmt.setDate(index++, dto.getAppointmentDate()==null ? null : new java.sql.Date( dto.getAppointmentDate().getTime() ) );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AppointmentQueueDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the appointment_queue table that match the criteria ''.
	 */
	public AppointmentQueue[] findAll() throws AppointmentQueueDaoException
	{
		return findByDynamicSelect( SQL_SELECT, null );
	}

	/** 
	 * Returns all rows from the appointment_queue table that match the criteria 'appointment_id = :appointmentId'.
	 */
	public AppointmentQueue[] findWhereAppointmentIdEquals(String appointmentId) throws AppointmentQueueDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE appointment_id = ? ORDER BY appointment_id", new Object[] { appointmentId } );
	}

	/** 
	 * Returns all rows from the appointment_queue table that match the criteria 'officer_id = :officerId'.
	 */
	public AppointmentQueue[] findWhereOfficerIdEquals(int officerId) throws AppointmentQueueDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE officer_id = ? ORDER BY officer_id", new Object[] {  new Integer(officerId) } );
	}

	/** 
	 * Returns all rows from the appointment_queue table that match the criteria 'appointment_date = :appointmentDate'.
	 */
	public AppointmentQueue[] findWhereAppointmentDateEquals(Date appointmentDate) throws AppointmentQueueDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE appointment_date = ? ORDER BY appointment_date", new Object[] { appointmentDate==null ? null : new java.sql.Date( appointmentDate.getTime() ) } );
	}

	/**
	 * Method 'AppointmentQueueDaoImpl'
	 * 
	 */
	public AppointmentQueueDaoImpl()
	{
	}

	/**
	 * Method 'AppointmentQueueDaoImpl'
	 * 
	 * @param userConn
	 */
	public AppointmentQueueDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "appointment_queue";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected AppointmentQueue fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			AppointmentQueue dto = new AppointmentQueue();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected AppointmentQueue[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			AppointmentQueue dto = new AppointmentQueue();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		AppointmentQueue ret[] = new AppointmentQueue[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(AppointmentQueue dto, ResultSet rs) throws SQLException
	{
		dto.setAppointmentId( rs.getString( COLUMN_APPOINTMENT_ID ) );
		dto.setOfficerId( rs.getInt( COLUMN_OFFICER_ID ) );
		dto.setAppointmentDate( rs.getDate(COLUMN_APPOINTMENT_DATE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(AppointmentQueue dto)
	{
	}

	/** 
	 * Returns all rows from the appointment_queue table that match the specified arbitrary SQL statement
	 */
	public AppointmentQueue[] findByDynamicSelect(String sql, Object[] sqlParams) throws AppointmentQueueDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AppointmentQueueDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the appointment_queue table that match the specified arbitrary SQL statement
	 */
	public AppointmentQueue[] findByDynamicWhere(String sql, Object[] sqlParams) throws AppointmentQueueDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new AppointmentQueueDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
