/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.jdbc;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.dto.*;
import org.nic.epanjeeyan.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class CancelledAppointmentsDaoImpl extends AbstractDAO implements CancelledAppointmentsDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT appointment_id, reason FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( appointment_id, reason ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET appointment_id = ?, reason = ? WHERE appointment_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE appointment_id = ?";

	/** 
	 * Index of column appointment_id
	 */
	protected static final int COLUMN_APPOINTMENT_ID = 1;

	/** 
	 * Index of column reason
	 */
	protected static final int COLUMN_REASON = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column appointment_id
	 */
	protected static final int PK_COLUMN_APPOINTMENT_ID = 1;

	/** 
	 * Inserts a new row in the cancelled_appointments table.
	 */
	public CancelledAppointmentsPk insert(CancelledAppointments dto) throws CancelledAppointmentsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setString( index++, dto.getAppointmentId() );
			stmt.setString( index++, dto.getReason() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CancelledAppointmentsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the cancelled_appointments table.
	 */
	public void update(CancelledAppointmentsPk pk, CancelledAppointments dto) throws CancelledAppointmentsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setString( index++, dto.getAppointmentId() );
			stmt.setString( index++, dto.getReason() );
			stmt.setString( 3, pk.getAppointmentId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CancelledAppointmentsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the cancelled_appointments table.
	 */
	public void delete(CancelledAppointmentsPk pk) throws CancelledAppointmentsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getAppointmentId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CancelledAppointmentsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the cancelled_appointments table that matches the specified primary-key value.
	 */
	public CancelledAppointments findByPrimaryKey(CancelledAppointmentsPk pk) throws CancelledAppointmentsDaoException
	{
		return findByPrimaryKey( pk.getAppointmentId() );
	}

	/** 
	 * Returns all rows from the cancelled_appointments table that match the criteria 'appointment_id = :appointmentId'.
	 */
	public CancelledAppointments findByPrimaryKey(String appointmentId) throws CancelledAppointmentsDaoException
	{
		CancelledAppointments ret[] = findByDynamicSelect( SQL_SELECT + " WHERE appointment_id = ?", new Object[] { appointmentId } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the cancelled_appointments table that match the criteria ''.
	 */
	public CancelledAppointments[] findAll() throws CancelledAppointmentsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY appointment_id", null );
	}

	/** 
	 * Returns all rows from the cancelled_appointments table that match the criteria 'appointment_id = :appointmentId'.
	 */
	public CancelledAppointments[] findWhereAppointmentIdEquals(String appointmentId) throws CancelledAppointmentsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE appointment_id = ? ORDER BY appointment_id", new Object[] { appointmentId } );
	}

	/** 
	 * Returns all rows from the cancelled_appointments table that match the criteria 'reason = :reason'.
	 */
	public CancelledAppointments[] findWhereReasonEquals(String reason) throws CancelledAppointmentsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE reason = ? ORDER BY reason", new Object[] { reason } );
	}

	/**
	 * Method 'CancelledAppointmentsDaoImpl'
	 * 
	 */
	public CancelledAppointmentsDaoImpl()
	{
	}

	/**
	 * Method 'CancelledAppointmentsDaoImpl'
	 * 
	 * @param userConn
	 */
	public CancelledAppointmentsDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "cancelled_appointments";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected CancelledAppointments fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			CancelledAppointments dto = new CancelledAppointments();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected CancelledAppointments[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			CancelledAppointments dto = new CancelledAppointments();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		CancelledAppointments ret[] = new CancelledAppointments[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(CancelledAppointments dto, ResultSet rs) throws SQLException
	{
		dto.setAppointmentId( rs.getString( COLUMN_APPOINTMENT_ID ) );
		dto.setReason( rs.getString( COLUMN_REASON ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(CancelledAppointments dto)
	{
	}

	/** 
	 * Returns all rows from the cancelled_appointments table that match the specified arbitrary SQL statement
	 */
	public CancelledAppointments[] findByDynamicSelect(String sql, Object[] sqlParams) throws CancelledAppointmentsDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		System.out.println("statement is ... " + stmt);
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CancelledAppointmentsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the cancelled_appointments table that match the specified arbitrary SQL statement
	 */
	public CancelledAppointments[] findByDynamicWhere(String sql, Object[] sqlParams) throws CancelledAppointmentsDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new CancelledAppointmentsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
