/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.jdbc;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.dto.*;
import org.nic.epanjeeyan.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class EgrasResponseDaoImpl extends AbstractDAO implements EgrasResponseDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id, departmentId, officeCode, grnNo, requestParameters, responseParameters, mobileNo, amount, cin, year FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id, departmentId, officeCode, grnNo, requestParameters, responseParameters, mobileNo, amount, cin, year ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id = ?, departmentId = ?, officeCode = ?, grnNo = ?, requestParameters = ?, responseParameters = ?, mobileNo = ?, amount = ?, cin = ?, year = ? WHERE id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id = ?";

	/** 
	 * Index of column id
	 */
	protected static final int COLUMN_ID = 1;

	/** 
	 * Index of column departmentId
	 */
	protected static final int COLUMN_DEPARTMENT_ID = 2;

	/** 
	 * Index of column officeCode
	 */
	protected static final int COLUMN_OFFICE_CODE = 3;

	/** 
	 * Index of column grnNo
	 */
	protected static final int COLUMN_GRN_NO = 4;

	/** 
	 * Index of column requestParameters
	 */
	protected static final int COLUMN_REQUEST_PARAMETERS = 5;

	/** 
	 * Index of column responseParameters
	 */
	protected static final int COLUMN_RESPONSE_PARAMETERS = 6;

	/** 
	 * Index of column mobileNo
	 */
	protected static final int COLUMN_MOBILE_NO = 7;

	/** 
	 * Index of column amount
	 */
	protected static final int COLUMN_AMOUNT = 8;

	/** 
	 * Index of column cin
	 */
	protected static final int COLUMN_CIN = 9;

	/** 
	 * Index of column year
	 */
	protected static final int COLUMN_YEAR = 10;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 10;

	/** 
	 * Index of primary-key column id
	 */
	protected static final int PK_COLUMN_ID = 1;

	/** 
	 * Inserts a new row in the egras_response table.
	 */
	public EgrasResponsePk insert(EgrasResponse dto) throws EgrasResponseDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getId() );
			stmt.setString( index++, dto.getDepartmentId() );
			stmt.setString( index++, dto.getOfficeCode() );
			stmt.setString( index++, dto.getGrnNo() );
			stmt.setString( index++, dto.getRequestParameters() );
			stmt.setString( index++, dto.getResponseParameters() );
			stmt.setInt( index++, dto.getMobileNo() );
			stmt.setInt( index++, dto.getAmount() );
			stmt.setString( index++, dto.getCin() );
			stmt.setInt( index++, dto.getYear() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EgrasResponseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the egras_response table.
	 */
	public void update(EgrasResponsePk pk, EgrasResponse dto) throws EgrasResponseDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getId() );
			stmt.setString( index++, dto.getDepartmentId() );
			stmt.setString( index++, dto.getOfficeCode() );
			stmt.setString( index++, dto.getGrnNo() );
			stmt.setString( index++, dto.getRequestParameters() );
			stmt.setString( index++, dto.getResponseParameters() );
			stmt.setInt( index++, dto.getMobileNo() );
			stmt.setInt( index++, dto.getAmount() );
			stmt.setString( index++, dto.getCin() );
			stmt.setInt( index++, dto.getYear() );
			stmt.setInt( 11, pk.getId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EgrasResponseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the egras_response table.
	 */
	public void delete(EgrasResponsePk pk) throws EgrasResponseDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EgrasResponseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the egras_response table that matches the specified primary-key value.
	 */
	public EgrasResponse findByPrimaryKey(EgrasResponsePk pk) throws EgrasResponseDaoException
	{
		return findByPrimaryKey( pk.getId() );
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria 'id = :id'.
	 */
	public EgrasResponse findByPrimaryKey(int id) throws EgrasResponseDaoException
	{
		EgrasResponse ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id = ?", new Object[] {  new Integer(id) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria ''.
	 */
	public EgrasResponse[] findAll() throws EgrasResponseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id", null );
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria 'id = :id'.
	 */
	public EgrasResponse[] findWhereIdEquals(int id) throws EgrasResponseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id = ? ORDER BY id", new Object[] {  new Integer(id) } );
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria 'departmentId = :departmentId'.
	 */
	public EgrasResponse[] findWhereDepartmentIdEquals(String departmentId) throws EgrasResponseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE departmentId = ? ORDER BY departmentId", new Object[] { departmentId } );
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria 'officeCode = :officeCode'.
	 */
	public EgrasResponse[] findWhereOfficeCodeEquals(String officeCode) throws EgrasResponseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE officeCode = ? ORDER BY officeCode", new Object[] { officeCode } );
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria 'grnNo = :grnNo'.
	 */
	public EgrasResponse[] findWhereGrnNoEquals(String grnNo) throws EgrasResponseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE grnNo = ? ORDER BY grnNo", new Object[] { grnNo } );
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria 'requestParameters = :requestParameters'.
	 */
	public EgrasResponse[] findWhereRequestParametersEquals(String requestParameters) throws EgrasResponseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE requestParameters = ? ORDER BY requestParameters", new Object[] { requestParameters } );
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria 'responseParameters = :responseParameters'.
	 */
	public EgrasResponse[] findWhereResponseParametersEquals(String responseParameters) throws EgrasResponseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE responseParameters = ? ORDER BY responseParameters", new Object[] { responseParameters } );
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria 'mobileNo = :mobileNo'.
	 */
	public EgrasResponse[] findWhereMobileNoEquals(int mobileNo) throws EgrasResponseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE mobileNo = ? ORDER BY mobileNo", new Object[] {  new Integer(mobileNo) } );
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria 'amount = :amount'.
	 */
	public EgrasResponse[] findWhereAmountEquals(int amount) throws EgrasResponseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE amount = ? ORDER BY amount", new Object[] {  new Integer(amount) } );
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria 'cin = :cin'.
	 */
	public EgrasResponse[] findWhereCinEquals(String cin) throws EgrasResponseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE cin = ? ORDER BY cin", new Object[] { cin } );
	}

	/** 
	 * Returns all rows from the egras_response table that match the criteria 'year = :year'.
	 */
	public EgrasResponse[] findWhereYearEquals(int year) throws EgrasResponseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE year = ? ORDER BY year", new Object[] {  new Integer(year) } );
	}

	/**
	 * Method 'EgrasResponseDaoImpl'
	 * 
	 */
	public EgrasResponseDaoImpl()
	{
	}

	/**
	 * Method 'EgrasResponseDaoImpl'
	 * 
	 * @param userConn
	 */
	public EgrasResponseDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "egras_response";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected EgrasResponse fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			EgrasResponse dto = new EgrasResponse();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected EgrasResponse[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			EgrasResponse dto = new EgrasResponse();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		EgrasResponse ret[] = new EgrasResponse[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(EgrasResponse dto, ResultSet rs) throws SQLException
	{
		dto.setId( rs.getInt( COLUMN_ID ) );
		dto.setDepartmentId( rs.getString( COLUMN_DEPARTMENT_ID ) );
		dto.setOfficeCode( rs.getString( COLUMN_OFFICE_CODE ) );
		dto.setGrnNo( rs.getString( COLUMN_GRN_NO ) );
		dto.setRequestParameters( rs.getString( COLUMN_REQUEST_PARAMETERS ) );
		dto.setResponseParameters( rs.getString( COLUMN_RESPONSE_PARAMETERS ) );
		dto.setMobileNo( rs.getInt( COLUMN_MOBILE_NO ) );
		dto.setAmount( rs.getInt( COLUMN_AMOUNT ) );
		dto.setCin( rs.getString( COLUMN_CIN ) );
		dto.setYear( rs.getInt( COLUMN_YEAR ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(EgrasResponse dto)
	{
	}

	/** 
	 * Returns all rows from the egras_response table that match the specified arbitrary SQL statement
	 */
	public EgrasResponse[] findByDynamicSelect(String sql, Object[] sqlParams) throws EgrasResponseDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EgrasResponseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the egras_response table that match the specified arbitrary SQL statement
	 */
	public EgrasResponse[] findByDynamicWhere(String sql, Object[] sqlParams) throws EgrasResponseDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EgrasResponseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
