/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.jdbc;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.dto.*;
import org.nic.epanjeeyan.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class MarriagefeeDaoImpl extends AbstractDAO implements MarriagefeeDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT feeName, feeValue FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( feeName, feeValue ) VALUES ( ?, ? )";

	/** 
	 * Index of column feeName
	 */
	protected static final int COLUMN_FEE_NAME = 1;

	/** 
	 * Index of column feeValue
	 */
	protected static final int COLUMN_FEE_VALUE = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Inserts a new row in the marriagefee table.
	 */
	public void insert(Marriagefee dto) throws MarriagefeeDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setString( index++, dto.getFeeName() );
			stmt.setInt( index++, dto.getFeeValue() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new MarriagefeeDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the marriagefee table that match the criteria ''.
	 */
	public Marriagefee[] findAll() throws MarriagefeeDaoException
	{
		return findByDynamicSelect( SQL_SELECT, null );
	}

	/** 
	 * Returns all rows from the marriagefee table that match the criteria 'feeName = :feeName'.
	 */
	public Marriagefee[] findWhereFeeNameEquals(String feeName) throws MarriagefeeDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE feeName = ? ORDER BY feeName", new Object[] { feeName } );
	}

	/** 
	 * Returns all rows from the marriagefee table that match the criteria 'feeValue = :feeValue'.
	 */
	public Marriagefee[] findWhereFeeValueEquals(int feeValue) throws MarriagefeeDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE feeValue = ? ORDER BY feeValue", new Object[] {  new Integer(feeValue) } );
	}

	/**
	 * Method 'MarriagefeeDaoImpl'
	 * 
	 */
	public MarriagefeeDaoImpl()
	{
	}

	/**
	 * Method 'MarriagefeeDaoImpl'
	 * 
	 * @param userConn
	 */
	public MarriagefeeDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "marriagefee";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Marriagefee fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Marriagefee dto = new Marriagefee();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Marriagefee[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Marriagefee dto = new Marriagefee();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Marriagefee ret[] = new Marriagefee[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Marriagefee dto, ResultSet rs) throws SQLException
	{
		dto.setFeeName( rs.getString( COLUMN_FEE_NAME ) );
		dto.setFeeValue( rs.getInt( COLUMN_FEE_VALUE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Marriagefee dto)
	{
	}

	/** 
	 * Returns all rows from the marriagefee table that match the specified arbitrary SQL statement
	 */
	public Marriagefee[] findByDynamicSelect(String sql, Object[] sqlParams) throws MarriagefeeDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new MarriagefeeDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the marriagefee table that match the specified arbitrary SQL statement
	 */
	public Marriagefee[] findByDynamicWhere(String sql, Object[] sqlParams) throws MarriagefeeDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new MarriagefeeDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
