/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class AppointmentDocuments implements Serializable
{
	/** 
	 * This attribute maps to the column slno in the appointment_documents table.
	 */
	protected int slno;

	/** 
	 * This attribute maps to the column appointment_id in the appointment_documents table.
	 */
	protected String appointmentId;

	/** 
	 * This attribute maps to the column document in the appointment_documents table.
	 */
	protected byte[] document;

	/**
	 * Method 'AppointmentDocuments'
	 * 
	 */
	public AppointmentDocuments()
	{
	}

	/**
	 * Method 'getSlno'
	 * 
	 * @return int
	 */
	public int getSlno()
	{
		return slno;
	}

	/**
	 * Method 'setSlno'
	 * 
	 * @param slno
	 */
	public void setSlno(int slno)
	{
		this.slno = slno;
	}

	/**
	 * Method 'getAppointmentId'
	 * 
	 * @return String
	 */
	public String getAppointmentId()
	{
		return appointmentId;
	}

	/**
	 * Method 'setAppointmentId'
	 * 
	 * @param appointmentId
	 */
	public void setAppointmentId(String appointmentId)
	{
		this.appointmentId = appointmentId;
	}

	/**
	 * Method 'getDocument'
	 * 
	 * @return byte[]
	 */
	public byte[] getDocument()
	{
		return document;
	}

	/**
	 * Method 'setDocument'
	 * 
	 * @param document
	 */
	public void setDocument(byte[] document)
	{
		this.document = document;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof AppointmentDocuments)) {
			return false;
		}
		
		final AppointmentDocuments _cast = (AppointmentDocuments) _other;
		if (slno != _cast.slno) {
			return false;
		}
		
		if (appointmentId == null ? _cast.appointmentId != appointmentId : !appointmentId.equals( _cast.appointmentId )) {
			return false;
		}
		
		if (document == null ? _cast.document != document : !document.equals( _cast.document )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + slno;
		if (appointmentId != null) {
			_hashCode = 29 * _hashCode + appointmentId.hashCode();
		}
		
		if (document != null) {
			_hashCode = 29 * _hashCode + document.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return AppointmentDocumentsPk
	 */
	public AppointmentDocumentsPk createPk()
	{
		return new AppointmentDocumentsPk(slno);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.AppointmentDocuments: " );
		ret.append( "slno=" + slno );
		ret.append( ", appointmentId=" + appointmentId );
		ret.append( ", document=" + document );
		return ret.toString();
	}

}
