/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class AppointmentDetails implements Serializable
{
	protected java.lang.String appointmentId;

	protected java.lang.String applicantName;

	protected java.util.Date appointmentDate;

	protected java.lang.String officerName;

	/**
	 * Method 'AppointmentDetails'
	 * 
	 */
	public AppointmentDetails()
	{
	}

	/**
	 * Method 'getAppointmentId'
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getAppointmentId()
	{
		return appointmentId;
	}

	/**
	 * Method 'setAppointmentId'
	 * 
	 * @param appointmentId
	 */
	public void setAppointmentId(java.lang.String appointmentId)
	{
		this.appointmentId = appointmentId;
	}

	/**
	 * Method 'getApplicantName'
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getApplicantName()
	{
		return applicantName;
	}

	/**
	 * Method 'setApplicantName'
	 * 
	 * @param applicantName
	 */
	public void setApplicantName(java.lang.String applicantName)
	{
		this.applicantName = applicantName;
	}

	/**
	 * Method 'getAppointmentDate'
	 * 
	 * @return java.util.Date
	 */
	public java.util.Date getAppointmentDate()
	{
		return appointmentDate;
	}

	/**
	 * Method 'setAppointmentDate'
	 * 
	 * @param appointmentDate
	 */
	public void setAppointmentDate(java.util.Date appointmentDate)
	{
		this.appointmentDate = appointmentDate;
	}

	/**
	 * Method 'getOfficerName'
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getOfficerName()
	{
		return officerName;
	}

	/**
	 * Method 'setOfficerName'
	 * 
	 * @param officerName
	 */
	public void setOfficerName(java.lang.String officerName)
	{
		this.officerName = officerName;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.AppointmentDetails: " );
		ret.append( "appointmentId=" + appointmentId );
		ret.append( ", applicantName=" + applicantName );
		ret.append( ", appointmentDate=" + appointmentDate );
		ret.append( ", officerName=" + officerName );
		return ret.toString();
	}

}
