/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class CancelledAppointments implements Serializable
{
	/** 
	 * This attribute maps to the column appointment_id in the cancelled_appointments table.
	 */
	protected String appointmentId;

	/** 
	 * This attribute maps to the column reason in the cancelled_appointments table.
	 */
	protected String reason;

	/**
	 * Method 'CancelledAppointments'
	 * 
	 */
	public CancelledAppointments()
	{
	}

	/**
	 * Method 'getAppointmentId'
	 * 
	 * @return String
	 */
	public String getAppointmentId()
	{
		return appointmentId;
	}

	/**
	 * Method 'setAppointmentId'
	 * 
	 * @param appointmentId
	 */
	public void setAppointmentId(String appointmentId)
	{
		this.appointmentId = appointmentId;
	}

	/**
	 * Method 'getReason'
	 * 
	 * @return String
	 */
	public String getReason()
	{
		return reason;
	}

	/**
	 * Method 'setReason'
	 * 
	 * @param reason
	 */
	public void setReason(String reason)
	{
		this.reason = reason;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CancelledAppointments)) {
			return false;
		}
		
		final CancelledAppointments _cast = (CancelledAppointments) _other;
		if (appointmentId == null ? _cast.appointmentId != appointmentId : !appointmentId.equals( _cast.appointmentId )) {
			return false;
		}
		
		if (reason == null ? _cast.reason != reason : !reason.equals( _cast.reason )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (appointmentId != null) {
			_hashCode = 29 * _hashCode + appointmentId.hashCode();
		}
		
		if (reason != null) {
			_hashCode = 29 * _hashCode + reason.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CancelledAppointmentsPk
	 */
	public CancelledAppointmentsPk createPk()
	{
		return new CancelledAppointmentsPk(appointmentId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.CancelledAppointments: " );
		ret.append( "appointmentId=" + appointmentId );
		ret.append( ", reason=" + reason );
		return ret.toString();
	}

}
