/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Category implements Serializable
{
	/** 
	 * This attribute maps to the column code in the category table.
	 */
	protected int code;

	/** 
	 * This attribute maps to the column deed_type in the category table.
	 */
	protected String deedType;

	/** 
	 * This attribute maps to the column sdcode in the category table.
	 */
	protected int sdcode;

	/** 
	 * This attribute maps to the column sub_deed_type in the category table.
	 */
	protected String subDeedType;

	/** 
	 * This attribute maps to the column rfee in the category table.
	 */
	protected int rfee;

	/** 
	 * This attribute represents whether the primitive attribute rfee is null.
	 */
	protected boolean rfeeNull = true;

	/** 
	 * This attribute maps to the column sfee in the category table.
	 */
	protected int sfee;

	/** 
	 * This attribute represents whether the primitive attribute sfee is null.
	 */
	protected boolean sfeeNull = true;

	/** 
	 * This attribute maps to the column dcat in the category table.
	 */
	protected String dcat;

	/** 
	 * This attribute maps to the column act in the category table.
	 */
	protected String act;

	/** 
	 * This attribute maps to the column finindex in the category table.
	 */
	protected String finindex;

	/** 
	 * This attribute maps to the column criteria in the category table.
	 */
	protected String criteria;

	/** 
	 * This attribute maps to the column scndprtyreqrd in the category table.
	 */
	protected int scndprtyreqrd;

	/**
	 * Method 'Category'
	 * 
	 */
	public Category()
	{
	}

	/**
	 * Method 'getCode'
	 * 
	 * @return int
	 */
	public int getCode()
	{
		return code;
	}

	/**
	 * Method 'setCode'
	 * 
	 * @param code
	 */
	public void setCode(int code)
	{
		this.code = code;
	}

	/**
	 * Method 'getDeedType'
	 * 
	 * @return String
	 */
	public String getDeedType()
	{
		return deedType;
	}

	/**
	 * Method 'setDeedType'
	 * 
	 * @param deedType
	 */
	public void setDeedType(String deedType)
	{
		this.deedType = deedType;
	}

	/**
	 * Method 'getSdcode'
	 * 
	 * @return int
	 */
	public int getSdcode()
	{
		return sdcode;
	}

	/**
	 * Method 'setSdcode'
	 * 
	 * @param sdcode
	 */
	public void setSdcode(int sdcode)
	{
		this.sdcode = sdcode;
	}

	/**
	 * Method 'getSubDeedType'
	 * 
	 * @return String
	 */
	public String getSubDeedType()
	{
		return subDeedType;
	}

	/**
	 * Method 'setSubDeedType'
	 * 
	 * @param subDeedType
	 */
	public void setSubDeedType(String subDeedType)
	{
		this.subDeedType = subDeedType;
	}

	/**
	 * Method 'getRfee'
	 * 
	 * @return int
	 */
	public int getRfee()
	{
		return rfee;
	}

	/**
	 * Method 'setRfee'
	 * 
	 * @param rfee
	 */
	public void setRfee(int rfee)
	{
		this.rfee = rfee;
		this.rfeeNull = false;
	}

	/**
	 * Method 'setRfeeNull'
	 * 
	 * @param value
	 */
	public void setRfeeNull(boolean value)
	{
		this.rfeeNull = value;
	}

	/**
	 * Method 'isRfeeNull'
	 * 
	 * @return boolean
	 */
	public boolean isRfeeNull()
	{
		return rfeeNull;
	}

	/**
	 * Method 'getSfee'
	 * 
	 * @return int
	 */
	public int getSfee()
	{
		return sfee;
	}

	/**
	 * Method 'setSfee'
	 * 
	 * @param sfee
	 */
	public void setSfee(int sfee)
	{
		this.sfee = sfee;
		this.sfeeNull = false;
	}

	/**
	 * Method 'setSfeeNull'
	 * 
	 * @param value
	 */
	public void setSfeeNull(boolean value)
	{
		this.sfeeNull = value;
	}

	/**
	 * Method 'isSfeeNull'
	 * 
	 * @return boolean
	 */
	public boolean isSfeeNull()
	{
		return sfeeNull;
	}

	/**
	 * Method 'getDcat'
	 * 
	 * @return String
	 */
	public String getDcat()
	{
		return dcat;
	}

	/**
	 * Method 'setDcat'
	 * 
	 * @param dcat
	 */
	public void setDcat(String dcat)
	{
		this.dcat = dcat;
	}

	/**
	 * Method 'getAct'
	 * 
	 * @return String
	 */
	public String getAct()
	{
		return act;
	}

	/**
	 * Method 'setAct'
	 * 
	 * @param act
	 */
	public void setAct(String act)
	{
		this.act = act;
	}

	/**
	 * Method 'getFinindex'
	 * 
	 * @return String
	 */
	public String getFinindex()
	{
		return finindex;
	}

	/**
	 * Method 'setFinindex'
	 * 
	 * @param finindex
	 */
	public void setFinindex(String finindex)
	{
		this.finindex = finindex;
	}

	/**
	 * Method 'getCriteria'
	 * 
	 * @return String
	 */
	public String getCriteria()
	{
		return criteria;
	}

	/**
	 * Method 'setCriteria'
	 * 
	 * @param criteria
	 */
	public void setCriteria(String criteria)
	{
		this.criteria = criteria;
	}

	/**
	 * Method 'getScndprtyreqrd'
	 * 
	 * @return int
	 */
	public int getScndprtyreqrd()
	{
		return scndprtyreqrd;
	}

	/**
	 * Method 'setScndprtyreqrd'
	 * 
	 * @param scndprtyreqrd
	 */
	public void setScndprtyreqrd(int scndprtyreqrd)
	{
		this.scndprtyreqrd = scndprtyreqrd;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Category)) {
			return false;
		}
		
		final Category _cast = (Category) _other;
		if (code != _cast.code) {
			return false;
		}
		
		if (deedType == null ? _cast.deedType != deedType : !deedType.equals( _cast.deedType )) {
			return false;
		}
		
		if (sdcode != _cast.sdcode) {
			return false;
		}
		
		if (subDeedType == null ? _cast.subDeedType != subDeedType : !subDeedType.equals( _cast.subDeedType )) {
			return false;
		}
		
		if (rfee != _cast.rfee) {
			return false;
		}
		
		if (rfeeNull != _cast.rfeeNull) {
			return false;
		}
		
		if (sfee != _cast.sfee) {
			return false;
		}
		
		if (sfeeNull != _cast.sfeeNull) {
			return false;
		}
		
		if (dcat == null ? _cast.dcat != dcat : !dcat.equals( _cast.dcat )) {
			return false;
		}
		
		if (act == null ? _cast.act != act : !act.equals( _cast.act )) {
			return false;
		}
		
		if (finindex == null ? _cast.finindex != finindex : !finindex.equals( _cast.finindex )) {
			return false;
		}
		
		if (criteria == null ? _cast.criteria != criteria : !criteria.equals( _cast.criteria )) {
			return false;
		}
		
		if (scndprtyreqrd != _cast.scndprtyreqrd) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + code;
		if (deedType != null) {
			_hashCode = 29 * _hashCode + deedType.hashCode();
		}
		
		_hashCode = 29 * _hashCode + sdcode;
		if (subDeedType != null) {
			_hashCode = 29 * _hashCode + subDeedType.hashCode();
		}
		
		_hashCode = 29 * _hashCode + rfee;
		_hashCode = 29 * _hashCode + (rfeeNull ? 1 : 0);
		_hashCode = 29 * _hashCode + sfee;
		_hashCode = 29 * _hashCode + (sfeeNull ? 1 : 0);
		if (dcat != null) {
			_hashCode = 29 * _hashCode + dcat.hashCode();
		}
		
		if (act != null) {
			_hashCode = 29 * _hashCode + act.hashCode();
		}
		
		if (finindex != null) {
			_hashCode = 29 * _hashCode + finindex.hashCode();
		}
		
		if (criteria != null) {
			_hashCode = 29 * _hashCode + criteria.hashCode();
		}
		
		_hashCode = 29 * _hashCode + scndprtyreqrd;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CategoryPk
	 */
	public CategoryPk createPk()
	{
		return new CategoryPk(code, sdcode);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.Category: " );
		ret.append( "code=" + code );
		ret.append( ", deedType=" + deedType );
		ret.append( ", sdcode=" + sdcode );
		ret.append( ", subDeedType=" + subDeedType );
		ret.append( ", rfee=" + rfee );
		ret.append( ", sfee=" + sfee );
		ret.append( ", dcat=" + dcat );
		ret.append( ", act=" + act );
		ret.append( ", finindex=" + finindex );
		ret.append( ", criteria=" + criteria );
		ret.append( ", scndprtyreqrd=" + scndprtyreqrd );
		return ret.toString();
	}

}
