/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Dbusers implements Serializable
{
	/** 
	 * This attribute maps to the column db_id in the dbusers table.
	 */
	protected int dbId;

	/** 
	 * This attribute maps to the column dbname in the dbusers table.
	 */
	protected String dbname;

	/** 
	 * This attribute maps to the column officename in the dbusers table.
	 */
	protected String officename;

	/** 
	 * This attribute maps to the column password in the dbusers table.
	 */
	protected String password;

	/** 
	 * This attribute maps to the column username in the dbusers table.
	 */
	protected String username;

	/** 
	 * This attribute maps to the column sro_code in the dbusers table.
	 */
	protected String sroCode;

	/** 
	 * This attribute maps to the column district_code in the dbusers table.
	 */
	protected String districtCode;

	/**
	 * Method 'Dbusers'
	 * 
	 */
	public Dbusers()
	{
	}

	/**
	 * Method 'getDbId'
	 * 
	 * @return int
	 */
	public int getDbId()
	{
		return dbId;
	}

	/**
	 * Method 'setDbId'
	 * 
	 * @param dbId
	 */
	public void setDbId(int dbId)
	{
		this.dbId = dbId;
	}

	/**
	 * Method 'getDbname'
	 * 
	 * @return String
	 */
	public String getDbname()
	{
		return dbname;
	}

	/**
	 * Method 'setDbname'
	 * 
	 * @param dbname
	 */
	public void setDbname(String dbname)
	{
		this.dbname = dbname;
	}

	/**
	 * Method 'getOfficename'
	 * 
	 * @return String
	 */
	public String getOfficename()
	{
		return officename;
	}

	/**
	 * Method 'setOfficename'
	 * 
	 * @param officename
	 */
	public void setOfficename(String officename)
	{
		this.officename = officename;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
	}

	/**
	 * Method 'getUsername'
	 * 
	 * @return String
	 */
	public String getUsername()
	{
		return username;
	}

	/**
	 * Method 'setUsername'
	 * 
	 * @param username
	 */
	public void setUsername(String username)
	{
		this.username = username;
	}

	/**
	 * Method 'getSroCode'
	 * 
	 * @return String
	 */
	public String getSroCode()
	{
		return sroCode;
	}

	/**
	 * Method 'setSroCode'
	 * 
	 * @param sroCode
	 */
	public void setSroCode(String sroCode)
	{
		this.sroCode = sroCode;
	}

	/**
	 * Method 'getDistrictCode'
	 * 
	 * @return String
	 */
	public String getDistrictCode()
	{
		return districtCode;
	}

	/**
	 * Method 'setDistrictCode'
	 * 
	 * @param districtCode
	 */
	public void setDistrictCode(String districtCode)
	{
		this.districtCode = districtCode;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Dbusers)) {
			return false;
		}
		
		final Dbusers _cast = (Dbusers) _other;
		if (dbId != _cast.dbId) {
			return false;
		}
		
		if (dbname == null ? _cast.dbname != dbname : !dbname.equals( _cast.dbname )) {
			return false;
		}
		
		if (officename == null ? _cast.officename != officename : !officename.equals( _cast.officename )) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		if (username == null ? _cast.username != username : !username.equals( _cast.username )) {
			return false;
		}
		
		if (sroCode == null ? _cast.sroCode != sroCode : !sroCode.equals( _cast.sroCode )) {
			return false;
		}
		
		if (districtCode == null ? _cast.districtCode != districtCode : !districtCode.equals( _cast.districtCode )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + dbId;
		if (dbname != null) {
			_hashCode = 29 * _hashCode + dbname.hashCode();
		}
		
		if (officename != null) {
			_hashCode = 29 * _hashCode + officename.hashCode();
		}
		
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		if (username != null) {
			_hashCode = 29 * _hashCode + username.hashCode();
		}
		
		if (sroCode != null) {
			_hashCode = 29 * _hashCode + sroCode.hashCode();
		}
		
		if (districtCode != null) {
			_hashCode = 29 * _hashCode + districtCode.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DbusersPk
	 */
	public DbusersPk createPk()
	{
		return new DbusersPk(dbId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.Dbusers: " );
		ret.append( "dbId=" + dbId );
		ret.append( ", dbname=" + dbname );
		ret.append( ", officename=" + officename );
		ret.append( ", password=" + password );
		ret.append( ", username=" + username );
		ret.append( ", sroCode=" + sroCode );
		ret.append( ", districtCode=" + districtCode );
		return ret.toString();
	}

}
