/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Deedtype implements Serializable
{
	/** 
	 * This attribute maps to the column code in the deedtype table.
	 */
	protected int code;

	/** 
	 * This attribute maps to the column section in the deedtype table.
	 */
	protected String section;

	/**
	 * Method 'Deedtype'
	 * 
	 */
	public Deedtype()
	{
	}

	/**
	 * Method 'getCode'
	 * 
	 * @return int
	 */
	public int getCode()
	{
		return code;
	}

	/**
	 * Method 'setCode'
	 * 
	 * @param code
	 */
	public void setCode(int code)
	{
		this.code = code;
	}

	/**
	 * Method 'getSection'
	 * 
	 * @return String
	 */
	public String getSection()
	{
		return section;
	}

	/**
	 * Method 'setSection'
	 * 
	 * @param section
	 */
	public void setSection(String section)
	{
		this.section = section;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Deedtype)) {
			return false;
		}
		
		final Deedtype _cast = (Deedtype) _other;
		if (code != _cast.code) {
			return false;
		}
		
		if (section == null ? _cast.section != section : !section.equals( _cast.section )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + code;
		if (section != null) {
			_hashCode = 29 * _hashCode + section.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DeedtypePk
	 */
	public DeedtypePk createPk()
	{
		return new DeedtypePk(code);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.Deedtype: " );
		ret.append( "code=" + code );
		ret.append( ", section=" + section );
		return ret.toString();
	}

}
