/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class LastOfficerAssigned implements Serializable
{
	protected int officer_id;

	/** 
	 * This attribute represents whether the primitive attribute officer_id is null.
	 */
	protected boolean officer_idNull = true;

	/**
	 * Method 'LastOfficerAssigned'
	 * 
	 */
	public LastOfficerAssigned()
	{
	}

	/**
	 * Method 'getOfficer_id'
	 * 
	 * @return int
	 */
	public int getOfficer_id()
	{
		return officer_id;
	}

	/**
	 * Method 'setOfficer_id'
	 * 
	 * @param officer_id
	 */
	public void setOfficer_id(int officer_id)
	{
		this.officer_id = officer_id;
	}

	/** 
	 * Sets the value of officer_idNull
	 */
	public void setOfficer_idNull(boolean officer_idNull)
	{
		this.officer_idNull = officer_idNull;
	}

	/** 
	 * Gets the value of officer_idNull
	 */
	public boolean isOfficer_idNull()
	{
		return officer_idNull;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.LastOfficerAssigned: " );
		ret.append( "officer_id=" + officer_id );
		return ret.toString();
	}

}
