/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Marriagetype implements Serializable
{
	/** 
	 * This attribute maps to the column marriageType in the marriagetype table.
	 */
	protected String marriageType;

	/**
	 * Method 'Marriagetype'
	 * 
	 */
	public Marriagetype()
	{
	}

	/**
	 * Method 'getMarriageType'
	 * 
	 * @return String
	 */
	public String getMarriageType()
	{
		return marriageType;
	}

	/**
	 * Method 'setMarriageType'
	 * 
	 * @param marriageType
	 */
	public void setMarriageType(String marriageType)
	{
		this.marriageType = marriageType;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Marriagetype)) {
			return false;
		}
		
		final Marriagetype _cast = (Marriagetype) _other;
		if (marriageType == null ? _cast.marriageType != marriageType : !marriageType.equals( _cast.marriageType )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (marriageType != null) {
			_hashCode = 29 * _hashCode + marriageType.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.Marriagetype: " );
		ret.append( "marriageType=" + marriageType );
		return ret.toString();
	}

}
