/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the nodal_officers table.
 */
public class NodalOfficersPk implements Serializable
{
	protected int officerId;

	/** 
	 * This attribute represents whether the primitive attribute officerId is null.
	 */
	protected boolean officerIdNull;

	/** 
	 * Sets the value of officerId
	 */
	public void setOfficerId(int officerId)
	{
		this.officerId = officerId;
	}

	/** 
	 * Gets the value of officerId
	 */
	public int getOfficerId()
	{
		return officerId;
	}

	/**
	 * Method 'NodalOfficersPk'
	 * 
	 */
	public NodalOfficersPk()
	{
	}

	/**
	 * Method 'NodalOfficersPk'
	 * 
	 * @param officerId
	 */
	public NodalOfficersPk(final int officerId)
	{
		this.officerId = officerId;
	}

	/** 
	 * Sets the value of officerIdNull
	 */
	public void setOfficerIdNull(boolean officerIdNull)
	{
		this.officerIdNull = officerIdNull;
	}

	/** 
	 * Gets the value of officerIdNull
	 */
	public boolean isOfficerIdNull()
	{
		return officerIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof NodalOfficersPk)) {
			return false;
		}
		
		final NodalOfficersPk _cast = (NodalOfficersPk) _other;
		if (officerId != _cast.officerId) {
			return false;
		}
		
		if (officerIdNull != _cast.officerIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + officerId;
		_hashCode = 29 * _hashCode + (officerIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.NodalOfficersPk: " );
		ret.append( "officerId=" + officerId );
		return ret.toString();
	}

}
