/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Nonencum implements Serializable
{
	/** 
	 * This attribute maps to the column srlno in the nonencum table.
	 */
	protected int srlno;

	/** 
	 * This attribute maps to the column slno in the nonencum table.
	 */
	protected int slno;

	/** 
	 * This attribute maps to the column applno in the nonencum table.
	 */
	protected String applno;

	/** 
	 * This attribute maps to the column appldate in the nonencum table.
	 */
	protected Date appldate;

	/** 
	 * This attribute maps to the column nmappl in the nonencum table.
	 */
	protected String nmappl;

	/** 
	 * This attribute maps to the column nmfather in the nonencum table.
	 */
	protected String nmfather;

	/** 
	 * This attribute maps to the column addr in the nonencum table.
	 */
	protected String addr;

	/** 
	 * This attribute maps to the column mcode in the nonencum table.
	 */
	protected String mcode;

	/** 
	 * This attribute maps to the column vlcode in the nonencum table.
	 */
	protected String vlcode;

	/** 
	 * This attribute maps to the column record1 in the nonencum table.
	 */
	protected Date record1;

	/** 
	 * This attribute maps to the column record2 in the nonencum table.
	 */
	protected Date record2;

	/** 
	 * This attribute maps to the column refno in the nonencum table.
	 */
	protected String refno;

	/** 
	 * This attribute maps to the column ref_yr in the nonencum table.
	 */
	protected String refYr;

	/** 
	 * This attribute maps to the column pattano in the nonencum table.
	 */
	protected String pattano;

	/** 
	 * This attribute maps to the column dagno in the nonencum table.
	 */
	protected String dagno;

	/** 
	 * This attribute maps to the column area in the nonencum table.
	 */
	protected String area;

	/** 
	 * This attribute maps to the column search in the nonencum table.
	 */
	protected String search;

	/** 
	 * This attribute maps to the column feeamt in the nonencum table.
	 */
	protected float feeamt;

	/** 
	 * This attribute represents whether the primitive attribute feeamt is null.
	 */
	protected boolean feeamtNull = true;

	/** 
	 * This attribute maps to the column issued in the nonencum table.
	 */
	protected short issued;

	/** 
	 * This attribute represents whether the primitive attribute issued is null.
	 */
	protected boolean issuedNull = true;

	/** 
	 * This attribute maps to the column fee_type in the nonencum table.
	 */
	protected String feeType;

	/**
	 * Method 'Nonencum'
	 * 
	 */
	public Nonencum()
	{
	}

	/**
	 * Method 'getSrlno'
	 * 
	 * @return int
	 */
	public int getSrlno()
	{
		return srlno;
	}

	/**
	 * Method 'setSrlno'
	 * 
	 * @param srlno
	 */
	public void setSrlno(int srlno)
	{
		this.srlno = srlno;
	}

	/**
	 * Method 'getSlno'
	 * 
	 * @return int
	 */
	public int getSlno()
	{
		return slno;
	}

	/**
	 * Method 'setSlno'
	 * 
	 * @param slno
	 */
	public void setSlno(int slno)
	{
		this.slno = slno;
	}

	/**
	 * Method 'getApplno'
	 * 
	 * @return String
	 */
	public String getApplno()
	{
		return applno;
	}

	/**
	 * Method 'setApplno'
	 * 
	 * @param applno
	 */
	public void setApplno(String applno)
	{
		this.applno = applno;
	}

	/**
	 * Method 'getAppldate'
	 * 
	 * @return Date
	 */
	public Date getAppldate()
	{
		return appldate;
	}

	/**
	 * Method 'setAppldate'
	 * 
	 * @param appldate
	 */
	public void setAppldate(Date appldate)
	{
		this.appldate = appldate;
	}

	/**
	 * Method 'getNmappl'
	 * 
	 * @return String
	 */
	public String getNmappl()
	{
		return nmappl;
	}

	/**
	 * Method 'setNmappl'
	 * 
	 * @param nmappl
	 */
	public void setNmappl(String nmappl)
	{
		this.nmappl = nmappl;
	}

	/**
	 * Method 'getNmfather'
	 * 
	 * @return String
	 */
	public String getNmfather()
	{
		return nmfather;
	}

	/**
	 * Method 'setNmfather'
	 * 
	 * @param nmfather
	 */
	public void setNmfather(String nmfather)
	{
		this.nmfather = nmfather;
	}

	/**
	 * Method 'getAddr'
	 * 
	 * @return String
	 */
	public String getAddr()
	{
		return addr;
	}

	/**
	 * Method 'setAddr'
	 * 
	 * @param addr
	 */
	public void setAddr(String addr)
	{
		this.addr = addr;
	}

	/**
	 * Method 'getMcode'
	 * 
	 * @return String
	 */
	public String getMcode()
	{
		return mcode;
	}

	/**
	 * Method 'setMcode'
	 * 
	 * @param mcode
	 */
	public void setMcode(String mcode)
	{
		this.mcode = mcode;
	}

	/**
	 * Method 'getVlcode'
	 * 
	 * @return String
	 */
	public String getVlcode()
	{
		return vlcode;
	}

	/**
	 * Method 'setVlcode'
	 * 
	 * @param vlcode
	 */
	public void setVlcode(String vlcode)
	{
		this.vlcode = vlcode;
	}

	/**
	 * Method 'getRecord1'
	 * 
	 * @return Date
	 */
	public Date getRecord1()
	{
		return record1;
	}

	/**
	 * Method 'setRecord1'
	 * 
	 * @param record1
	 */
	public void setRecord1(Date record1)
	{
		this.record1 = record1;
	}

	/**
	 * Method 'getRecord2'
	 * 
	 * @return Date
	 */
	public Date getRecord2()
	{
		return record2;
	}

	/**
	 * Method 'setRecord2'
	 * 
	 * @param record2
	 */
	public void setRecord2(Date record2)
	{
		this.record2 = record2;
	}

	/**
	 * Method 'getRefno'
	 * 
	 * @return String
	 */
	public String getRefno()
	{
		return refno;
	}

	/**
	 * Method 'setRefno'
	 * 
	 * @param refno
	 */
	public void setRefno(String refno)
	{
		this.refno = refno;
	}

	/**
	 * Method 'getRefYr'
	 * 
	 * @return String
	 */
	public String getRefYr()
	{
		return refYr;
	}

	/**
	 * Method 'setRefYr'
	 * 
	 * @param refYr
	 */
	public void setRefYr(String refYr)
	{
		this.refYr = refYr;
	}

	/**
	 * Method 'getPattano'
	 * 
	 * @return String
	 */
	public String getPattano()
	{
		return pattano;
	}

	/**
	 * Method 'setPattano'
	 * 
	 * @param pattano
	 */
	public void setPattano(String pattano)
	{
		this.pattano = pattano;
	}

	/**
	 * Method 'getDagno'
	 * 
	 * @return String
	 */
	public String getDagno()
	{
		return dagno;
	}

	/**
	 * Method 'setDagno'
	 * 
	 * @param dagno
	 */
	public void setDagno(String dagno)
	{
		this.dagno = dagno;
	}

	/**
	 * Method 'getArea'
	 * 
	 * @return String
	 */
	public String getArea()
	{
		return area;
	}

	/**
	 * Method 'setArea'
	 * 
	 * @param area
	 */
	public void setArea(String area)
	{
		this.area = area;
	}

	/**
	 * Method 'getSearch'
	 * 
	 * @return String
	 */
	public String getSearch()
	{
		return search;
	}

	/**
	 * Method 'setSearch'
	 * 
	 * @param search
	 */
	public void setSearch(String search)
	{
		this.search = search;
	}

	/**
	 * Method 'getFeeamt'
	 * 
	 * @return float
	 */
	public float getFeeamt()
	{
		return feeamt;
	}

	/**
	 * Method 'setFeeamt'
	 * 
	 * @param feeamt
	 */
	public void setFeeamt(float feeamt)
	{
		this.feeamt = feeamt;
		this.feeamtNull = false;
	}

	/**
	 * Method 'setFeeamtNull'
	 * 
	 * @param value
	 */
	public void setFeeamtNull(boolean value)
	{
		this.feeamtNull = value;
	}

	/**
	 * Method 'isFeeamtNull'
	 * 
	 * @return boolean
	 */
	public boolean isFeeamtNull()
	{
		return feeamtNull;
	}

	/**
	 * Method 'getIssued'
	 * 
	 * @return short
	 */
	public short getIssued()
	{
		return issued;
	}

	/**
	 * Method 'setIssued'
	 * 
	 * @param issued
	 */
	public void setIssued(short issued)
	{
		this.issued = issued;
		this.issuedNull = false;
	}

	/**
	 * Method 'setIssuedNull'
	 * 
	 * @param value
	 */
	public void setIssuedNull(boolean value)
	{
		this.issuedNull = value;
	}

	/**
	 * Method 'isIssuedNull'
	 * 
	 * @return boolean
	 */
	public boolean isIssuedNull()
	{
		return issuedNull;
	}

	/**
	 * Method 'getFeeType'
	 * 
	 * @return String
	 */
	public String getFeeType()
	{
		return feeType;
	}

	/**
	 * Method 'setFeeType'
	 * 
	 * @param feeType
	 */
	public void setFeeType(String feeType)
	{
		this.feeType = feeType;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Nonencum)) {
			return false;
		}
		
		final Nonencum _cast = (Nonencum) _other;
		if (srlno != _cast.srlno) {
			return false;
		}
		
		if (slno != _cast.slno) {
			return false;
		}
		
		if (applno == null ? _cast.applno != applno : !applno.equals( _cast.applno )) {
			return false;
		}
		
		if (appldate == null ? _cast.appldate != appldate : !appldate.equals( _cast.appldate )) {
			return false;
		}
		
		if (nmappl == null ? _cast.nmappl != nmappl : !nmappl.equals( _cast.nmappl )) {
			return false;
		}
		
		if (nmfather == null ? _cast.nmfather != nmfather : !nmfather.equals( _cast.nmfather )) {
			return false;
		}
		
		if (addr == null ? _cast.addr != addr : !addr.equals( _cast.addr )) {
			return false;
		}
		
		if (mcode == null ? _cast.mcode != mcode : !mcode.equals( _cast.mcode )) {
			return false;
		}
		
		if (vlcode == null ? _cast.vlcode != vlcode : !vlcode.equals( _cast.vlcode )) {
			return false;
		}
		
		if (record1 == null ? _cast.record1 != record1 : !record1.equals( _cast.record1 )) {
			return false;
		}
		
		if (record2 == null ? _cast.record2 != record2 : !record2.equals( _cast.record2 )) {
			return false;
		}
		
		if (refno == null ? _cast.refno != refno : !refno.equals( _cast.refno )) {
			return false;
		}
		
		if (refYr == null ? _cast.refYr != refYr : !refYr.equals( _cast.refYr )) {
			return false;
		}
		
		if (pattano == null ? _cast.pattano != pattano : !pattano.equals( _cast.pattano )) {
			return false;
		}
		
		if (dagno == null ? _cast.dagno != dagno : !dagno.equals( _cast.dagno )) {
			return false;
		}
		
		if (area == null ? _cast.area != area : !area.equals( _cast.area )) {
			return false;
		}
		
		if (search == null ? _cast.search != search : !search.equals( _cast.search )) {
			return false;
		}
		
		if (feeamt != _cast.feeamt) {
			return false;
		}
		
		if (feeamtNull != _cast.feeamtNull) {
			return false;
		}
		
		if (issued != _cast.issued) {
			return false;
		}
		
		if (issuedNull != _cast.issuedNull) {
			return false;
		}
		
		if (feeType == null ? _cast.feeType != feeType : !feeType.equals( _cast.feeType )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + srlno;
		_hashCode = 29 * _hashCode + slno;
		if (applno != null) {
			_hashCode = 29 * _hashCode + applno.hashCode();
		}
		
		if (appldate != null) {
			_hashCode = 29 * _hashCode + appldate.hashCode();
		}
		
		if (nmappl != null) {
			_hashCode = 29 * _hashCode + nmappl.hashCode();
		}
		
		if (nmfather != null) {
			_hashCode = 29 * _hashCode + nmfather.hashCode();
		}
		
		if (addr != null) {
			_hashCode = 29 * _hashCode + addr.hashCode();
		}
		
		if (mcode != null) {
			_hashCode = 29 * _hashCode + mcode.hashCode();
		}
		
		if (vlcode != null) {
			_hashCode = 29 * _hashCode + vlcode.hashCode();
		}
		
		if (record1 != null) {
			_hashCode = 29 * _hashCode + record1.hashCode();
		}
		
		if (record2 != null) {
			_hashCode = 29 * _hashCode + record2.hashCode();
		}
		
		if (refno != null) {
			_hashCode = 29 * _hashCode + refno.hashCode();
		}
		
		if (refYr != null) {
			_hashCode = 29 * _hashCode + refYr.hashCode();
		}
		
		if (pattano != null) {
			_hashCode = 29 * _hashCode + pattano.hashCode();
		}
		
		if (dagno != null) {
			_hashCode = 29 * _hashCode + dagno.hashCode();
		}
		
		if (area != null) {
			_hashCode = 29 * _hashCode + area.hashCode();
		}
		
		if (search != null) {
			_hashCode = 29 * _hashCode + search.hashCode();
		}
		
		_hashCode = 29 * _hashCode + Float.floatToIntBits(feeamt);
		_hashCode = 29 * _hashCode + (feeamtNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) issued;
		_hashCode = 29 * _hashCode + (issuedNull ? 1 : 0);
		if (feeType != null) {
			_hashCode = 29 * _hashCode + feeType.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return NonencumPk
	 */
	public NonencumPk createPk()
	{
		return new NonencumPk(srlno, applno);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.Nonencum: " );
		ret.append( "srlno=" + srlno );
		ret.append( ", slno=" + slno );
		ret.append( ", applno=" + applno );
		ret.append( ", appldate=" + appldate );
		ret.append( ", nmappl=" + nmappl );
		ret.append( ", nmfather=" + nmfather );
		ret.append( ", addr=" + addr );
		ret.append( ", mcode=" + mcode );
		ret.append( ", vlcode=" + vlcode );
		ret.append( ", record1=" + record1 );
		ret.append( ", record2=" + record2 );
		ret.append( ", refno=" + refno );
		ret.append( ", refYr=" + refYr );
		ret.append( ", pattano=" + pattano );
		ret.append( ", dagno=" + dagno );
		ret.append( ", area=" + area );
		ret.append( ", search=" + search );
		ret.append( ", feeamt=" + feeamt );
		ret.append( ", issued=" + issued );
		ret.append( ", feeType=" + feeType );
		return ret.toString();
	}

}
