/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class OffDays implements Serializable
{
	/** 
	 * This attribute maps to the column id in the off_days table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column dist_code in the off_days table.
	 */
	protected String distCode;

	/** 
	 * This attribute maps to the column sro_code in the off_days table.
	 */
	protected String sroCode;

	/** 
	 * This attribute maps to the column date in the off_days table.
	 */
	protected Date date;

	/**
	 * Method 'OffDays'
	 * 
	 */
	public OffDays()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getDistCode'
	 * 
	 * @return String
	 */
	public String getDistCode()
	{
		return distCode;
	}

	/**
	 * Method 'setDistCode'
	 * 
	 * @param distCode
	 */
	public void setDistCode(String distCode)
	{
		this.distCode = distCode;
	}

	/**
	 * Method 'getSroCode'
	 * 
	 * @return String
	 */
	public String getSroCode()
	{
		return sroCode;
	}

	/**
	 * Method 'setSroCode'
	 * 
	 * @param sroCode
	 */
	public void setSroCode(String sroCode)
	{
		this.sroCode = sroCode;
	}

	/**
	 * Method 'getDate'
	 * 
	 * @return Date
	 */
	public Date getDate()
	{
		return date;
	}

	/**
	 * Method 'setDate'
	 * 
	 * @param date
	 */
	public void setDate(Date date)
	{
		this.date = date;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof OffDays)) {
			return false;
		}
		
		final OffDays _cast = (OffDays) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (distCode == null ? _cast.distCode != distCode : !distCode.equals( _cast.distCode )) {
			return false;
		}
		
		if (sroCode == null ? _cast.sroCode != sroCode : !sroCode.equals( _cast.sroCode )) {
			return false;
		}
		
		if (date == null ? _cast.date != date : !date.equals( _cast.date )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (distCode != null) {
			_hashCode = 29 * _hashCode + distCode.hashCode();
		}
		
		if (sroCode != null) {
			_hashCode = 29 * _hashCode + sroCode.hashCode();
		}
		
		if (date != null) {
			_hashCode = 29 * _hashCode + date.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return OffDaysPk
	 */
	public OffDaysPk createPk()
	{
		return new OffDaysPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.OffDays: " );
		ret.append( "id=" + id );
		ret.append( ", distCode=" + distCode );
		ret.append( ", sroCode=" + sroCode );
		ret.append( ", date=" + date );
		return ret.toString();
	}

}
