/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class OfficeTreasuryMapping implements Serializable
{
	/** 
	 * This attribute maps to the column id in the office_treasury_mapping table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column db_id in the office_treasury_mapping table.
	 */
	protected int dbId;

	/** 
	 * This attribute maps to the column office_code in the office_treasury_mapping table.
	 */
	protected String officeCode;

	/** 
	 * This attribute maps to the column treasury_code in the office_treasury_mapping table.
	 */
	protected String treasuryCode;

	/**
	 * Method 'OfficeTreasuryMapping'
	 * 
	 */
	public OfficeTreasuryMapping()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getDbId'
	 * 
	 * @return int
	 */
	public int getDbId()
	{
		return dbId;
	}

	/**
	 * Method 'setDbId'
	 * 
	 * @param dbId
	 */
	public void setDbId(int dbId)
	{
		this.dbId = dbId;
	}

	/**
	 * Method 'getOfficeCode'
	 * 
	 * @return String
	 */
	public String getOfficeCode()
	{
		return officeCode;
	}

	/**
	 * Method 'setOfficeCode'
	 * 
	 * @param officeCode
	 */
	public void setOfficeCode(String officeCode)
	{
		this.officeCode = officeCode;
	}

	/**
	 * Method 'getTreasuryCode'
	 * 
	 * @return String
	 */
	public String getTreasuryCode()
	{
		return treasuryCode;
	}

	/**
	 * Method 'setTreasuryCode'
	 * 
	 * @param treasuryCode
	 */
	public void setTreasuryCode(String treasuryCode)
	{
		this.treasuryCode = treasuryCode;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof OfficeTreasuryMapping)) {
			return false;
		}
		
		final OfficeTreasuryMapping _cast = (OfficeTreasuryMapping) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (dbId != _cast.dbId) {
			return false;
		}
		
		if (officeCode == null ? _cast.officeCode != officeCode : !officeCode.equals( _cast.officeCode )) {
			return false;
		}
		
		if (treasuryCode == null ? _cast.treasuryCode != treasuryCode : !treasuryCode.equals( _cast.treasuryCode )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + dbId;
		if (officeCode != null) {
			_hashCode = 29 * _hashCode + officeCode.hashCode();
		}
		
		if (treasuryCode != null) {
			_hashCode = 29 * _hashCode + treasuryCode.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return OfficeTreasuryMappingPk
	 */
	public OfficeTreasuryMappingPk createPk()
	{
		return new OfficeTreasuryMappingPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.OfficeTreasuryMapping: " );
		ret.append( "id=" + id );
		ret.append( ", dbId=" + dbId );
		ret.append( ", officeCode=" + officeCode );
		ret.append( ", treasuryCode=" + treasuryCode );
		return ret.toString();
	}

}
