/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the party table.
 */
public class PartyPk implements Serializable
{
	protected Integer slno;

	protected String partyComcaseno;

	protected String partytype;

	/** 
	 * Sets the value of slno
	 */
	public void setSlno(Integer slno)
	{
		this.slno = slno;
	}

	/** 
	 * Gets the value of slno
	 */
	public Integer getSlno()
	{
		return slno;
	}

	/** 
	 * Sets the value of partyComcaseno
	 */
	public void setPartyComcaseno(String partyComcaseno)
	{
		this.partyComcaseno = partyComcaseno;
	}

	/** 
	 * Gets the value of partyComcaseno
	 */
	public String getPartyComcaseno()
	{
		return partyComcaseno;
	}

	/** 
	 * Sets the value of partytype
	 */
	public void setPartytype(String partytype)
	{
		this.partytype = partytype;
	}

	/** 
	 * Gets the value of partytype
	 */
	public String getPartytype()
	{
		return partytype;
	}

	/**
	 * Method 'PartyPk'
	 * 
	 */
	public PartyPk()
	{
	}

	/**
	 * Method 'PartyPk'
	 * 
	 * @param slno
	 * @param partyComcaseno
	 * @param partytype
	 */
	public PartyPk(final Integer slno, final String partyComcaseno, final String partytype)
	{
		this.slno = slno;
		this.partyComcaseno = partyComcaseno;
		this.partytype = partytype;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PartyPk)) {
			return false;
		}
		
		final PartyPk _cast = (PartyPk) _other;
		if (slno == null ? _cast.slno != slno : !slno.equals( _cast.slno )) {
			return false;
		}
		
		if (partyComcaseno == null ? _cast.partyComcaseno != partyComcaseno : !partyComcaseno.equals( _cast.partyComcaseno )) {
			return false;
		}
		
		if (partytype == null ? _cast.partytype != partytype : !partytype.equals( _cast.partytype )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (slno != null) {
			_hashCode = 29 * _hashCode + slno.hashCode();
		}
		
		if (partyComcaseno != null) {
			_hashCode = 29 * _hashCode + partyComcaseno.hashCode();
		}
		
		if (partytype != null) {
			_hashCode = 29 * _hashCode + partytype.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.PartyPk: " );
		ret.append( "slno=" + slno );
		ret.append( ", partyComcaseno=" + partyComcaseno );
		ret.append( ", partytype=" + partytype );
		return ret.toString();
	}

}
