/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Partytype implements Serializable
{
	/** 
	 * This attribute maps to the column type in the partytype table.
	 */
	protected String type;

	/** 
	 * This attribute maps to the column first_or_sec in the partytype table.
	 */
	protected String firstOrSec;

	/**
	 * Method 'Partytype'
	 * 
	 */
	public Partytype()
	{
	}

	/**
	 * Method 'getType'
	 * 
	 * @return String
	 */
	public String getType()
	{
		return type;
	}

	/**
	 * Method 'setType'
	 * 
	 * @param type
	 */
	public void setType(String type)
	{
		this.type = type;
	}

	/**
	 * Method 'getFirstOrSec'
	 * 
	 * @return String
	 */
	public String getFirstOrSec()
	{
		return firstOrSec;
	}

	/**
	 * Method 'setFirstOrSec'
	 * 
	 * @param firstOrSec
	 */
	public void setFirstOrSec(String firstOrSec)
	{
		this.firstOrSec = firstOrSec;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Partytype)) {
			return false;
		}
		
		final Partytype _cast = (Partytype) _other;
		if (type == null ? _cast.type != type : !type.equals( _cast.type )) {
			return false;
		}
		
		if (firstOrSec == null ? _cast.firstOrSec != firstOrSec : !firstOrSec.equals( _cast.firstOrSec )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (type != null) {
			_hashCode = 29 * _hashCode + type.hashCode();
		}
		
		if (firstOrSec != null) {
			_hashCode = 29 * _hashCode + firstOrSec.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.Partytype: " );
		ret.append( "type=" + type );
		ret.append( ", firstOrSec=" + firstOrSec );
		return ret.toString();
	}

}
