/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Renquiry implements Serializable
{
	
	protected Integer slno;
	protected boolean slnoNull = true;
	protected String tmpcaseno;
	protected String applicantName;
	protected String areaType;
	protected Date enquiryDate;
	protected Integer deedType;
        protected boolean deedTypeNull = true;
	protected String deedSubtype;
	protected Integer considerationAmount;
	protected boolean considerationAmountNull = true;
	protected Integer registrationFee;
	protected boolean registrationFeeNull = true;
	protected Integer stampDuty;
	protected boolean stampDutyNull = true;
	protected String documentToBeFurnished;
	protected String docSubject;
	protected Integer whetherLand;
	protected String gender;
	protected String act;
	public Renquiry()
	{
	}
	public Integer getSlno()
	{
		return slno;
	}
	public void setSlno(Integer slno)
	{
		this.slno = slno;
		this.slnoNull = false;
	}
	public void setSlnoNull(boolean value)
	{
		this.slnoNull = value;
	}
	public boolean isSlnoNull()
	{
		return slnoNull;
	}
	public String getTmpcaseno()
	{
		return tmpcaseno;
	}
	public void setTmpcaseno(String tmpcaseno)
	{
		this.tmpcaseno = tmpcaseno;
	}
	public String getApplicantName()
	{
		return applicantName;
	}
	public void setApplicantName(String applicantName)
	{
		this.applicantName = applicantName;
	}
	public String getAreaType()
	{
		return areaType;
	}
	public void setAreaType(String areaType)
	{
		this.areaType = areaType;
	}
	public Date getEnquiryDate()
	{
		return enquiryDate;
	}
	public void setEnquiryDate(Date enquiryDate)
	{
		this.enquiryDate = enquiryDate;
	}
	public Integer getDeedType()
	{
		return deedType;
	}
	public void setDeedType(Integer deedType)
	{
		this.deedType = deedType;
		this.deedTypeNull = false;
	}
	public void setDeedTypeNull(boolean value)
	{
		this.deedTypeNull = value;
	}
	public boolean isDeedTypeNull()
	{
		return deedTypeNull;
	}
	public String getDeedSubtype()
	{
		return deedSubtype;
	}
	public void setDeedSubtype(String deedSubtype)
	{
		this.deedSubtype = deedSubtype;
	}
	public Integer getConsiderationAmount()
	{
		return considerationAmount;
	}
	public void setConsiderationAmount(Integer considerationAmount)
	{
		this.considerationAmount = considerationAmount;
		this.considerationAmountNull = false;
	}
	public void setConsiderationAmountNull(boolean value)
	{
		this.considerationAmountNull = value;
	}
	public boolean isConsiderationAmountNull()
	{
		return considerationAmountNull;
	}
	public Integer getRegistrationFee()
	{
		return registrationFee;
	}
	public void setRegistrationFee(Integer registrationFee)
	{
		this.registrationFee = registrationFee;
		this.registrationFeeNull = false;
	}
	public void setRegistrationFeeNull(boolean value)
	{
		this.registrationFeeNull = value;
	}
	public boolean isRegistrationFeeNull()
	{
		return registrationFeeNull;
	}
	public Integer getStampDuty()
	{
		return stampDuty;
	}
	public void setStampDuty(Integer stampDuty)
	{
		this.stampDuty = stampDuty;
		this.stampDutyNull = false;
	}
	public void setStampDutyNull(boolean value)
	{
		this.stampDutyNull = value;
	}
	public boolean isStampDutyNull()
	{
		return stampDutyNull;
	}
	public String getDocumentToBeFurnished()
	{
		return documentToBeFurnished;
	}
	public void setDocumentToBeFurnished(String documentToBeFurnished)
	{
		this.documentToBeFurnished = documentToBeFurnished;
	}
	public String getDocSubject()
	{
		return docSubject;
	}
	public void setDocSubject(String docSubject)
	{
		this.docSubject = docSubject;
	}
	public Integer getWhetherLand()
	{
		return whetherLand;
	}
	public void setWhetherLand(Integer whetherLand)
	{
		this.whetherLand = whetherLand;
	}
	public String getGender()
	{
		return gender;
	}
	public void setGender(String gender)
	{
		this.gender = gender;
	}
	public String getAct()
	{
		return act;
	}
	public void setAct(String act)
	{
		this.act = act;
	}
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Renquiry)) {
			return false;
		}
		
		final Renquiry _cast = (Renquiry) _other;
		if (slno != _cast.slno) {
			return false;
		}
		
		if (slnoNull != _cast.slnoNull) {
			return false;
		}
		
		if (tmpcaseno == null ? _cast.tmpcaseno != tmpcaseno : !tmpcaseno.equals( _cast.tmpcaseno )) {
			return false;
		}
		
		if (applicantName == null ? _cast.applicantName != applicantName : !applicantName.equals( _cast.applicantName )) {
			return false;
		}
		
		if (areaType == null ? _cast.areaType != areaType : !areaType.equals( _cast.areaType )) {
			return false;
		}
		
		if (enquiryDate == null ? _cast.enquiryDate != enquiryDate : !enquiryDate.equals( _cast.enquiryDate )) {
			return false;
		}
		
		if (deedType != _cast.deedType) {
			return false;
		}
		
		if (deedTypeNull != _cast.deedTypeNull) {
			return false;
		}
		
		if (deedSubtype == null ? _cast.deedSubtype != deedSubtype : !deedSubtype.equals( _cast.deedSubtype )) {
			return false;
		}
		
		if (considerationAmount != _cast.considerationAmount) {
			return false;
		}
		
		if (considerationAmountNull != _cast.considerationAmountNull) {
			return false;
		}
		
		if (registrationFee != _cast.registrationFee) {
			return false;
		}
		
		if (registrationFeeNull != _cast.registrationFeeNull) {
			return false;
		}
		
		if (stampDuty != _cast.stampDuty) {
			return false;
		}
		
		if (stampDutyNull != _cast.stampDutyNull) {
			return false;
		}
		
		if (documentToBeFurnished == null ? _cast.documentToBeFurnished != documentToBeFurnished : !documentToBeFurnished.equals( _cast.documentToBeFurnished )) {
			return false;
		}
		
		if (docSubject == null ? _cast.docSubject != docSubject : !docSubject.equals( _cast.docSubject )) {
			return false;
		}
		
		if (whetherLand != _cast.whetherLand) {
			return false;
		}
		
		if (gender == null ? _cast.gender != gender : !gender.equals( _cast.gender )) {
			return false;
		}
		
		if (act == null ? _cast.act != act : !act.equals( _cast.act )) {
			return false;
		}
		
		return true;
	}
        
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + slno;
		_hashCode = 29 * _hashCode + (slnoNull ? 1 : 0);
		if (tmpcaseno != null) {
			_hashCode = 29 * _hashCode + tmpcaseno.hashCode();
		}
		
		if (applicantName != null) {
			_hashCode = 29 * _hashCode + applicantName.hashCode();
		}
		
		if (areaType != null) {
			_hashCode = 29 * _hashCode + areaType.hashCode();
		}
		
		if (enquiryDate != null) {
			_hashCode = 29 * _hashCode + enquiryDate.hashCode();
		}
		
		_hashCode = 29 * _hashCode + deedType;
		_hashCode = 29 * _hashCode + (deedTypeNull ? 1 : 0);
		if (deedSubtype != null) {
			_hashCode = 29 * _hashCode + deedSubtype.hashCode();
		}
		
		_hashCode = 29 * _hashCode + considerationAmount;
		_hashCode = 29 * _hashCode + (considerationAmountNull ? 1 : 0);
		_hashCode = 29 * _hashCode + registrationFee;
		_hashCode = 29 * _hashCode + (registrationFeeNull ? 1 : 0);
		_hashCode = 29 * _hashCode + stampDuty;
		_hashCode = 29 * _hashCode + (stampDutyNull ? 1 : 0);
		if (documentToBeFurnished != null) {
			_hashCode = 29 * _hashCode + documentToBeFurnished.hashCode();
		}
		
		if (docSubject != null) {
			_hashCode = 29 * _hashCode + docSubject.hashCode();
		}
		
		_hashCode = 29 * _hashCode + whetherLand;
		if (gender != null) {
			_hashCode = 29 * _hashCode + gender.hashCode();
		}
		
		if (act != null) {
			_hashCode = 29 * _hashCode + act.hashCode();
		}
		
		return _hashCode;
	}

	
	public RenquiryPk createPk()
	{
		return new RenquiryPk(tmpcaseno);
	}
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.Renquiry: " );
		ret.append( "slno=" + slno );
		ret.append( ", tmpcaseno=" + tmpcaseno );
		ret.append( ", applicantName=" + applicantName );
		ret.append( ", areaType=" + areaType );
		ret.append( ", enquiryDate=" + enquiryDate );
		ret.append( ", deedType=" + deedType );
		ret.append( ", deedSubtype=" + deedSubtype );
		ret.append( ", considerationAmount=" + considerationAmount );
		ret.append( ", registrationFee=" + registrationFee );
		ret.append( ", stampDuty=" + stampDuty );
		ret.append( ", documentToBeFurnished=" + documentToBeFurnished );
		ret.append( ", docSubject=" + docSubject );
		ret.append( ", whetherLand=" + whetherLand );
		ret.append( ", gender=" + gender );
		ret.append( ", act=" + act );
		return ret.toString();
	}

    public void setDeedSubtype(String[] C) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
