/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class SroOffices implements Serializable
{
	/** 
	 * This attribute maps to the column id in the sro_offices table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column office_name in the sro_offices table.
	 */
	protected String officeName;

	/**
	 * Method 'SroOffices'
	 * 
	 */
	public SroOffices()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getOfficeName'
	 * 
	 * @return String
	 */
	public String getOfficeName()
	{
		return officeName;
	}

	/**
	 * Method 'setOfficeName'
	 * 
	 * @param officeName
	 */
	public void setOfficeName(String officeName)
	{
		this.officeName = officeName;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof SroOffices)) {
			return false;
		}
		
		final SroOffices _cast = (SroOffices) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (officeName == null ? _cast.officeName != officeName : !officeName.equals( _cast.officeName )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (officeName != null) {
			_hashCode = 29 * _hashCode + officeName.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return SroOfficesPk
	 */
	public SroOfficesPk createPk()
	{
		return new SroOfficesPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.SroOffices: " );
		ret.append( "id=" + id );
		ret.append( ", officeName=" + officeName );
		return ret.toString();
	}

}
