/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class UserNew implements Serializable
{
	/** 
	 * This attribute maps to the column userid in the user_new table.
	 */
	protected String userid;

	/** 
	 * This attribute maps to the column username in the user_new table.
	 */
	protected String username;

	/** 
	 * This attribute maps to the column password in the user_new table.
	 */
	protected String password;

	/** 
	 * This attribute maps to the column password1 in the user_new table.
	 */
	protected String password1;

	/** 
	 * This attribute maps to the column password2 in the user_new table.
	 */
	protected String password2;

	/** 
	 * This attribute maps to the column password3 in the user_new table.
	 */
	protected String password3;

	/** 
	 * This attribute maps to the column password4 in the user_new table.
	 */
	protected String password4;

	/** 
	 * This attribute maps to the column designation in the user_new table.
	 */
	protected String designation;

	/** 
	 * This attribute maps to the column operator in the user_new table.
	 */
	protected int operator;

	/** 
	 * This attribute maps to the column accountant in the user_new table.
	 */
	protected int accountant;

	/** 
	 * This attribute maps to the column ro in the user_new table.
	 */
	protected int ro;

	/** 
	 * This attribute maps to the column assistant in the user_new table.
	 */
	protected int assistant;

	/** 
	 * This attribute maps to the column admin in the user_new table.
	 */
	protected int admin;

	/** 
	 * This attribute maps to the column helpdesk in the user_new table.
	 */
	protected int helpdesk;

	/**
	 * Method 'UserNew'
	 * 
	 */
	public UserNew()
	{
	}

	/**
	 * Method 'getUserid'
	 * 
	 * @return String
	 */
	public String getUserid()
	{
		return userid;
	}

	/**
	 * Method 'setUserid'
	 * 
	 * @param userid
	 */
	public void setUserid(String userid)
	{
		this.userid = userid;
	}

	/**
	 * Method 'getUsername'
	 * 
	 * @return String
	 */
	public String getUsername()
	{
		return username;
	}

	/**
	 * Method 'setUsername'
	 * 
	 * @param username
	 */
	public void setUsername(String username)
	{
		this.username = username;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
	}

	/**
	 * Method 'getPassword1'
	 * 
	 * @return String
	 */
	public String getPassword1()
	{
		return password1;
	}

	/**
	 * Method 'setPassword1'
	 * 
	 * @param password1
	 */
	public void setPassword1(String password1)
	{
		this.password1 = password1;
	}

	/**
	 * Method 'getPassword2'
	 * 
	 * @return String
	 */
	public String getPassword2()
	{
		return password2;
	}

	/**
	 * Method 'setPassword2'
	 * 
	 * @param password2
	 */
	public void setPassword2(String password2)
	{
		this.password2 = password2;
	}

	/**
	 * Method 'getPassword3'
	 * 
	 * @return String
	 */
	public String getPassword3()
	{
		return password3;
	}

	/**
	 * Method 'setPassword3'
	 * 
	 * @param password3
	 */
	public void setPassword3(String password3)
	{
		this.password3 = password3;
	}

	/**
	 * Method 'getPassword4'
	 * 
	 * @return String
	 */
	public String getPassword4()
	{
		return password4;
	}

	/**
	 * Method 'setPassword4'
	 * 
	 * @param password4
	 */
	public void setPassword4(String password4)
	{
		this.password4 = password4;
	}

	/**
	 * Method 'getDesignation'
	 * 
	 * @return String
	 */
	public String getDesignation()
	{
		return designation;
	}

	/**
	 * Method 'setDesignation'
	 * 
	 * @param designation
	 */
	public void setDesignation(String designation)
	{
		this.designation = designation;
	}

	/**
	 * Method 'getOperator'
	 * 
	 * @return int
	 */
	public int getOperator()
	{
		return operator;
	}

	/**
	 * Method 'setOperator'
	 * 
	 * @param operator
	 */
	public void setOperator(int operator)
	{
		this.operator = operator;
	}

	/**
	 * Method 'getAccountant'
	 * 
	 * @return int
	 */
	public int getAccountant()
	{
		return accountant;
	}

	/**
	 * Method 'setAccountant'
	 * 
	 * @param accountant
	 */
	public void setAccountant(int accountant)
	{
		this.accountant = accountant;
	}

	/**
	 * Method 'getRo'
	 * 
	 * @return int
	 */
	public int getRo()
	{
		return ro;
	}

	/**
	 * Method 'setRo'
	 * 
	 * @param ro
	 */
	public void setRo(int ro)
	{
		this.ro = ro;
	}

	/**
	 * Method 'getAssistant'
	 * 
	 * @return int
	 */
	public int getAssistant()
	{
		return assistant;
	}

	/**
	 * Method 'setAssistant'
	 * 
	 * @param assistant
	 */
	public void setAssistant(int assistant)
	{
		this.assistant = assistant;
	}

	/**
	 * Method 'getAdmin'
	 * 
	 * @return int
	 */
	public int getAdmin()
	{
		return admin;
	}

	/**
	 * Method 'setAdmin'
	 * 
	 * @param admin
	 */
	public void setAdmin(int admin)
	{
		this.admin = admin;
	}

	/**
	 * Method 'getHelpdesk'
	 * 
	 * @return int
	 */
	public int getHelpdesk()
	{
		return helpdesk;
	}

	/**
	 * Method 'setHelpdesk'
	 * 
	 * @param helpdesk
	 */
	public void setHelpdesk(int helpdesk)
	{
		this.helpdesk = helpdesk;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof UserNew)) {
			return false;
		}
		
		final UserNew _cast = (UserNew) _other;
		if (userid == null ? _cast.userid != userid : !userid.equals( _cast.userid )) {
			return false;
		}
		
		if (username == null ? _cast.username != username : !username.equals( _cast.username )) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		if (password1 == null ? _cast.password1 != password1 : !password1.equals( _cast.password1 )) {
			return false;
		}
		
		if (password2 == null ? _cast.password2 != password2 : !password2.equals( _cast.password2 )) {
			return false;
		}
		
		if (password3 == null ? _cast.password3 != password3 : !password3.equals( _cast.password3 )) {
			return false;
		}
		
		if (password4 == null ? _cast.password4 != password4 : !password4.equals( _cast.password4 )) {
			return false;
		}
		
		if (designation == null ? _cast.designation != designation : !designation.equals( _cast.designation )) {
			return false;
		}
		
		if (operator != _cast.operator) {
			return false;
		}
		
		if (accountant != _cast.accountant) {
			return false;
		}
		
		if (ro != _cast.ro) {
			return false;
		}
		
		if (assistant != _cast.assistant) {
			return false;
		}
		
		if (admin != _cast.admin) {
			return false;
		}
		
		if (helpdesk != _cast.helpdesk) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (userid != null) {
			_hashCode = 29 * _hashCode + userid.hashCode();
		}
		
		if (username != null) {
			_hashCode = 29 * _hashCode + username.hashCode();
		}
		
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		if (password1 != null) {
			_hashCode = 29 * _hashCode + password1.hashCode();
		}
		
		if (password2 != null) {
			_hashCode = 29 * _hashCode + password2.hashCode();
		}
		
		if (password3 != null) {
			_hashCode = 29 * _hashCode + password3.hashCode();
		}
		
		if (password4 != null) {
			_hashCode = 29 * _hashCode + password4.hashCode();
		}
		
		if (designation != null) {
			_hashCode = 29 * _hashCode + designation.hashCode();
		}
		
		_hashCode = 29 * _hashCode + operator;
		_hashCode = 29 * _hashCode + accountant;
		_hashCode = 29 * _hashCode + ro;
		_hashCode = 29 * _hashCode + assistant;
		_hashCode = 29 * _hashCode + admin;
		_hashCode = 29 * _hashCode + helpdesk;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UserNewPk
	 */
	public UserNewPk createPk()
	{
		return new UserNewPk(userid);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.UserNew: " );
		ret.append( "userid=" + userid );
		ret.append( ", username=" + username );
		ret.append( ", password=" + password );
		ret.append( ", password1=" + password1 );
		ret.append( ", password2=" + password2 );
		ret.append( ", password3=" + password3 );
		ret.append( ", password4=" + password4 );
		ret.append( ", designation=" + designation );
		ret.append( ", operator=" + operator );
		ret.append( ", accountant=" + accountant );
		ret.append( ", ro=" + ro );
		ret.append( ", assistant=" + assistant );
		ret.append( ", admin=" + admin );
		ret.append( ", helpdesk=" + helpdesk );
		return ret.toString();
	}

}
