/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import org.nic.epanjeeyan.dao.*;
import org.nic.epanjeeyan.factory.*;
import org.nic.epanjeeyan.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Vilcode implements Serializable
{
	/** 
	 * This attribute maps to the column vlcode in the vilcode table.
	 */
	protected String vlcode;

	/** 
	 * This attribute maps to the column vlname in the vilcode table.
	 */
	protected String vlname;

	/** 
	 * This attribute maps to the column vltype in the vilcode table.
	 */
	protected String vltype;

	/**
	 * Method 'Vilcode'
	 * 
	 */
	public Vilcode()
	{
	}

	/**
	 * Method 'getVlcode'
	 * 
	 * @return String
	 */
	public String getVlcode()
	{
		return vlcode;
	}

	/**
	 * Method 'setVlcode'
	 * 
	 * @param vlcode
	 */
	public void setVlcode(String vlcode)
	{
		this.vlcode = vlcode;
	}

	/**
	 * Method 'getVlname'
	 * 
	 * @return String
	 */
	public String getVlname()
	{
		return vlname;
	}

	/**
	 * Method 'setVlname'
	 * 
	 * @param vlname
	 */
	public void setVlname(String vlname)
	{
		this.vlname = vlname;
	}

	/**
	 * Method 'getVltype'
	 * 
	 * @return String
	 */
	public String getVltype()
	{
		return vltype;
	}

	/**
	 * Method 'setVltype'
	 * 
	 * @param vltype
	 */
	public void setVltype(String vltype)
	{
		this.vltype = vltype;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Vilcode)) {
			return false;
		}
		
		final Vilcode _cast = (Vilcode) _other;
		if (vlcode == null ? _cast.vlcode != vlcode : !vlcode.equals( _cast.vlcode )) {
			return false;
		}
		
		if (vlname == null ? _cast.vlname != vlname : !vlname.equals( _cast.vlname )) {
			return false;
		}
		
		if (vltype == null ? _cast.vltype != vltype : !vltype.equals( _cast.vltype )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (vlcode != null) {
			_hashCode = 29 * _hashCode + vlcode.hashCode();
		}
		
		if (vlname != null) {
			_hashCode = 29 * _hashCode + vlname.hashCode();
		}
		
		if (vltype != null) {
			_hashCode = 29 * _hashCode + vltype.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return VilcodePk
	 */
	public VilcodePk createPk()
	{
		return new VilcodePk(vlcode);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.Vilcode: " );
		ret.append( "vlcode=" + vlcode );
		ret.append( ", vlname=" + vlname );
		ret.append( ", vltype=" + vltype );
		return ret.toString();
	}

}
