/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the witness table.
 */
public class WitnessPk implements Serializable
{
	protected int slno;

	protected String comcaseno;

	protected String wtype;

	/** 
	 * This attribute represents whether the primitive attribute slno is null.
	 */
	protected boolean slnoNull;

	/** 
	 * Sets the value of slno
	 */
	public void setSlno(int slno)
	{
		this.slno = slno;
	}

	/** 
	 * Gets the value of slno
	 */
	public int getSlno()
	{
		return slno;
	}

	/** 
	 * Sets the value of comcaseno
	 */
	public void setComcaseno(String comcaseno)
	{
		this.comcaseno = comcaseno;
	}

	/** 
	 * Gets the value of comcaseno
	 */
	public String getComcaseno()
	{
		return comcaseno;
	}

	/** 
	 * Sets the value of wtype
	 */
	public void setWtype(String wtype)
	{
		this.wtype = wtype;
	}

	/** 
	 * Gets the value of wtype
	 */
	public String getWtype()
	{
		return wtype;
	}

	/**
	 * Method 'WitnessPk'
	 * 
	 */
	public WitnessPk()
	{
	}

	/**
	 * Method 'WitnessPk'
	 * 
	 * @param slno
	 * @param comcaseno
	 * @param wtype
	 */
	public WitnessPk(final int slno, final String comcaseno, final String wtype)
	{
		this.slno = slno;
		this.comcaseno = comcaseno;
		this.wtype = wtype;
	}

	/** 
	 * Sets the value of slnoNull
	 */
	public void setSlnoNull(boolean slnoNull)
	{
		this.slnoNull = slnoNull;
	}

	/** 
	 * Gets the value of slnoNull
	 */
	public boolean isSlnoNull()
	{
		return slnoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof WitnessPk)) {
			return false;
		}
		
		final WitnessPk _cast = (WitnessPk) _other;
		if (slno != _cast.slno) {
			return false;
		}
		
		if (comcaseno == null ? _cast.comcaseno != comcaseno : !comcaseno.equals( _cast.comcaseno )) {
			return false;
		}
		
		if (wtype == null ? _cast.wtype != wtype : !wtype.equals( _cast.wtype )) {
			return false;
		}
		
		if (slnoNull != _cast.slnoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + slno;
		if (comcaseno != null) {
			_hashCode = 29 * _hashCode + comcaseno.hashCode();
		}
		
		if (wtype != null) {
			_hashCode = 29 * _hashCode + wtype.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (slnoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "org.nic.epanjeeyan.dto.WitnessPk: " );
		ret.append( "slno=" + slno );
		ret.append( ", comcaseno=" + comcaseno );
		ret.append( ", wtype=" + wtype );
		return ret.toString();
	}

}
