/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dao;

import org.nic.epanjeeyan.dto.*;
import org.nic.epanjeeyan.exceptions.*;

public interface DistrictDao
{
	/** 
	 * Inserts a new row in the district table.
	 */
	public void insert(District dto) throws DistrictDaoException;

	/** 
	 * Returns all rows from the district table that match the criteria ''.
	 */
	public District[] findAll() throws DistrictDaoException;

	/** 
	 * Returns all rows from the district table that match the criteria 'distname = :distname'.
	 */
	public District[] findWhereDistnameEquals(String distname) throws DistrictDaoException;

	/** 
	 * Returns all rows from the district table that match the criteria 'distcode = :distcode'.
	 */
	public District[] findWhereDistcodeEquals(String distcode) throws DistrictDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the district table that match the specified arbitrary SQL statement
	 */
	public District[] findByDynamicSelect(String sql, Object[] sqlParams) throws DistrictDaoException;

	/** 
	 * Returns all rows from the district table that match the specified arbitrary SQL statement
	 */
	public District[] findByDynamicWhere(String sql, Object[] sqlParams) throws DistrictDaoException;

}
