/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package org.nic.epanjeeyan.dao;

import org.nic.epanjeeyan.dto.*;
import org.nic.epanjeeyan.exceptions.*;

public interface MarriagetypeDao
{
	/** 
	 * Inserts a new row in the marriagetype table.
	 */
	public void insert(Marriagetype dto) throws MarriagetypeDaoException;

	/** 
	 * Returns all rows from the marriagetype table that match the criteria ''.
	 */
	public Marriagetype[] findAll() throws MarriagetypeDaoException;

	/** 
	 * Returns all rows from the marriagetype table that match the criteria 'marriageType = :marriageType'.
	 */
	public Marriagetype[] findWhereMarriageTypeEquals(String marriageType) throws MarriagetypeDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the marriagetype table that match the specified arbitrary SQL statement
	 */
	public Marriagetype[] findByDynamicSelect(String sql, Object[] sqlParams) throws MarriagetypeDaoException;

	/** 
	 * Returns all rows from the marriagetype table that match the specified arbitrary SQL statement
	 */
	public Marriagetype[] findByDynamicWhere(String sql, Object[] sqlParams) throws MarriagetypeDaoException;

}
